# Generated by Django 2.0.5 on 2018-06-06 07:00

from django.db import migrations, models
import django.utils.timezone
import lostandfoundapp.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_or_found', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('title', models.CharField(help_text='e.g Lost mobile at 210 lab.', max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('contact_person_name', models.CharField(max_length=20)),
                ('contact_person_mobile_or_email', models.CharField(max_length=30, validators=[lostandfoundapp.validations.validate_person_email_or_contact])),
                ('date_found_or_lost', models.DateField(verbose_name='lost or found date ')),
                ('date_published', models.DateField(default=django.utils.timezone.now, verbose_name='published date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=10)),
                ('date_solved', models.DateField(blank=True, null=True, verbose_name='solved date')),
                ('author', models.CharField(default='Parvez', max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
