# Generated by Django 2.0.5 on 2018-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='author_email',
            field=models.CharField(default='2016parvez.mullah@ves.ac.in', max_length=50),
        ),
    ]
