# Generated by Django 2.0.5 on 2018-06-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0002_lostandfound_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='author',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='author_email',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
