# Generated by Django 2.0.5 on 2018-06-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0003_auto_20180608_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='author_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
